# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import viev
import model
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    # Конструктор интрефейса
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(473, 392)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbt_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_1.setGeometry(QtCore.QRect(10, 50, 85, 31))
        self.pbt_1.setObjectName("pbt_1")
        self.pbt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_2.setGeometry(QtCore.QRect(100, 50, 91, 31))
        self.pbt_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbt_2.setAcceptDrops(False)
        self.pbt_2.setAutoFillBackground(False)
        self.pbt_2.setCheckable(False)
        self.pbt_2.setAutoRepeat(False)
        self.pbt_2.setAutoExclusive(False)
        self.pbt_2.setObjectName("pbt_2")
        self.pbt_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_3.setGeometry(QtCore.QRect(200, 50, 85, 31))
        self.pbt_3.setObjectName("pbt_3")
        self.pbt_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_4.setGeometry(QtCore.QRect(290, 50, 85, 31))
        self.pbt_4.setObjectName("pbt_4")
        self.pbt_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_5.setGeometry(QtCore.QRect(380, 50, 85, 31))
        self.pbt_5.setObjectName("pbt_5")
        self.Plain_edit_text = QtWidgets.QLineEdit(self.centralwidget)
        self.Plain_edit_text.setGeometry(QtCore.QRect(10, 10, 451, 31))
        self.Plain_edit_text.setObjectName("Plain_edit_text")
        self.label1 = QtWidgets.QListWidget(self.centralwidget)
        self.label1.setEnabled(True)
        self.label1.setGeometry(QtCore.QRect(10, 90, 451, 281))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label1.setFont(font)
        self.label1.setMouseTracking(False)
        self.label1.setTabletTracking(False)
        self.label1.setAcceptDrops(False)
        self.label1.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.label1.addItems("")
        # self.label1.setScaledContents(False)
        # self.label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        # self.label1.setWordWrap(False)
        # self.label1.setIndent(-2)
        # self.label1.setObjectName("label1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_function() # переходим к функциональной функции


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbt_1.setText(_translate("MainWindow", "Архив"))
        self.pbt_2.setText(_translate("MainWindow", "Добавить"))
        self.pbt_3.setText(_translate("MainWindow", "Поиск"))
        self.pbt_4.setText(_translate("MainWindow", "Изменить"))
        self.pbt_5.setText(_translate("MainWindow", "Удалить"))
#### редактировать!
    # -*- coding: utf-8 -*-

    # Form implementation generated from reading ui file 'GUI1.ui'
    #
    # Created by: PyQt5 UI code generator 5.15.9
    #
    # WARNING: Any manual changes made to this file will be lost when pyuic5 is
    # run again.  Do not edit this file unless you know what you are doing.

    from PyQt5 import QtCore, QtGui, QtWidgets

    class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(510, 417)
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.pbt_1 = QtWidgets.QPushButton(self.centralwidget)
            self.pbt_1.setGeometry(QtCore.QRect(10, 50, 71, 31))
            self.pbt_1.setObjectName("pbt_1")
            self.pbt_2 = QtWidgets.QPushButton(self.centralwidget)
            self.pbt_2.setGeometry(QtCore.QRect(90, 50, 121, 31))
            self.pbt_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
            self.pbt_2.setAcceptDrops(False)
            self.pbt_2.setAutoFillBackground(False)
            self.pbt_2.setCheckable(False)
            self.pbt_2.setAutoRepeat(False)
            self.pbt_2.setAutoExclusive(False)
            self.pbt_2.setObjectName("pbt_2")
            self.pbt_3 = QtWidgets.QPushButton(self.centralwidget)
            self.pbt_3.setGeometry(QtCore.QRect(220, 50, 71, 31))
            self.pbt_3.setObjectName("pbt_3")
            self.pbt_4 = QtWidgets.QPushButton(self.centralwidget)
            self.pbt_4.setGeometry(QtCore.QRect(300, 50, 111, 31))
            self.pbt_4.setObjectName("pbt_4")
            self.pbt_5 = QtWidgets.QPushButton(self.centralwidget)
            self.pbt_5.setGeometry(QtCore.QRect(420, 50, 71, 31))
            self.pbt_5.setObjectName("pbt_5")
            self.listWidget_1 = QtWidgets.QListWidget(self.centralwidget)
            self.listWidget_1.setGeometry(QtCore.QRect(10, 90, 481, 311))
            self.listWidget_1.setObjectName("listWidget_1")
            self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
            self.lineEdit.setGeometry(QtCore.QRect(10, 10, 481, 31))
            self.lineEdit.setObjectName("lineEdit")
            MainWindow.setCentralWidget(self.centralwidget)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)
            self.add_function()

        def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.pbt_1.setText(_translate("MainWindow", "Архив"))
            self.pbt_2.setText(_translate("MainWindow", "Добавить данные"))
            self.pbt_3.setText(_translate("MainWindow", "Поиск по ФИ"))
            self.pbt_4.setText(_translate("MainWindow", "Изменить номер"))
            self.pbt_5.setText(_translate("MainWindow", "Удалить"))

        def add_function(self):
            self.text = ""
            self.lineEdit.setPlaceholderText("Введите текст")
            # выводим весь текст из файла
            self.pbt_1.clicked.connect(lambda: self.write_label(self.text))
            # извлекаю данные из Строчки и передаю их
            # Вводи нового текста в файл
            self.pbt_2.clicked.connect(lambda: self.onChanged( self.lineEdit.text()))
            # Динамическое отслеживание введенного текст
            # self.lineEdit.textChanged[str].connect(self.onChanged)


        # Функция вывода на экран всех пользователей
        def write_label(self, text):
            self.listWidget_1.addItem(f"{text}")
            with open("test.txt", "r", encoding="UTF-8") as self.file1:
                self.fl = self.file1.readlines()
                for i in self.fl:
                    # выводим информацию на экран
                    self.str0 = i.split(";")
                    self.str1 = self.str0[0]
                    self.str2 = self.str0[1]
                    self.listWidget_1.addItem(f"{self.str1} | {self.str2 }")

        # Функция добавления нового пользователя
        def onChanged(self, text):
            with open("test.txt", "a", encoding="UTF-8") as self.file1:
                self.file1.write(text+"\n")


        def return_pressed(self):
            print("!!!!")

    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

    def model_get_data(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
