# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import viev
import model
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    # Конструктор интрефейса
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(473, 392)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbt_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_1.setGeometry(QtCore.QRect(10, 50, 85, 31))
        self.pbt_1.setObjectName("pbt_1")
        self.pbt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_2.setGeometry(QtCore.QRect(100, 50, 91, 31))
        self.pbt_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbt_2.setAcceptDrops(False)
        self.pbt_2.setAutoFillBackground(False)
        self.pbt_2.setCheckable(False)
        self.pbt_2.setAutoRepeat(False)
        self.pbt_2.setAutoExclusive(False)
        self.pbt_2.setObjectName("pbt_2")
        self.pbt_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_3.setGeometry(QtCore.QRect(200, 50, 85, 31))
        self.pbt_3.setObjectName("pbt_3")
        self.pbt_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_4.setGeometry(QtCore.QRect(290, 50, 85, 31))
        self.pbt_4.setObjectName("pbt_4")
        self.pbt_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pbt_5.setGeometry(QtCore.QRect(380, 50, 85, 31))
        self.pbt_5.setObjectName("pbt_5")
        self.Plain_edit_text = QtWidgets.QLineEdit(self.centralwidget)
        self.Plain_edit_text.setGeometry(QtCore.QRect(10, 10, 451, 31))
        self.Plain_edit_text.setObjectName("Plain_edit_text")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setEnabled(True)
        self.label1.setGeometry(QtCore.QRect(10, 90, 451, 281))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label1.setFont(font)
        self.label1.setMouseTracking(False)
        self.label1.setTabletTracking(False)
        self.label1.setAcceptDrops(False)
        self.label1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label1.setText("")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label1.setWordWrap(False)
        self.label1.setIndent(-2)
        self.label1.setObjectName("label1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_function() # переходим к функциональной функции


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbt_1.setText(_translate("MainWindow", "Архив"))
        self.pbt_2.setText(_translate("MainWindow", "Добавить"))
        self.pbt_3.setText(_translate("MainWindow", "Поиск"))
        self.pbt_4.setText(_translate("MainWindow", "Изменить"))
        self.pbt_5.setText(_translate("MainWindow", "Удалить"))
#### редактировать!
    def add_function(self):
        self.str1 = self.Plain_edit_text.text()
        # self.str1 = self.Plain_edit_text.toPlainText()
        print(self.str1)
        self.pbt_1.clicked.connect(lambda: model.get_data())
        # self.pbt_2.clicked.connect(lambda: model.add_contact(str1))
        self.pbt_3.clicked.connect(lambda: model.find(self.str1))
        self.label1.setText(self.str1)

    def model_get_data(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
